// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DCM.Specflow.Features.Create_Model
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Create Model")]
    [NUnit.Framework.CategoryAttribute("chrome")]
    [NUnit.Framework.CategoryAttribute("SanityTest")]
    public partial class CreateModelFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "createmodel.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Create Model", "\t\tDCM login with Chrome browser and verify DCM functionality ", ProgrammingLanguage.CSharp, new string[] {
                        "chrome",
                        "SanityTest"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01 Create model")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void _01CreateModel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 Create model", null, new string[] {
                        "mytag"});
#line 7
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
 testRunner.Given("click on create model tab from dashboard and click on Create Model using Free For" +
                    "m from popup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Area2",
                        "Area3",
                        "Forecasted_Annual_Arrivals",
                        "Current_LWBS_rate",
                        "Admit_Percentage"});
            table2.AddRow(new string[] {
                        "FT",
                        "PIT",
                        "80000",
                        "3",
                        "12"});
#line 9
 testRunner.And("enter values into Practice Metrics fields and click on next button or click on Ar" +
                    "rivals/ESL", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "FT_ESI_3",
                        "PIT_ESI_3"});
            table3.AddRow(new string[] {
                        "20",
                        "5"});
#line 13
 testRunner.When("Arrivals/ESL tab opens enter values into fields and click on next button or click" +
                    " on Length of Stay", ((string)(null)), table3, "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Overall_Admit_LOS",
                        "Overall_Arrival_To_Admit_Decision",
                        "Main_Discharge_LOS",
                        "FT_Discharge_LOS",
                        "PIT_Discharge_LOS"});
            table4.AddRow(new string[] {
                        "120",
                        "60",
                        "90",
                        "30",
                        "30"});
#line 17
 testRunner.And("Length of Stay tab opens enter values into fields and click on next button or cli" +
                    "ck on Shifts", ((string)(null)), table4, "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "From_Time",
                        "To_Time"});
            table5.AddRow(new string[] {
                        "01:00",
                        "08:00"});
#line 21
 testRunner.When("Shifts tab opens enter values into fields and click on next button or click on Cl" +
                    "inician Productivity", ((string)(null)), table5, "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "main_phy_pph",
                        "main_app_pph",
                        "main_PhyFirstHour",
                        "main_appFirstHour",
                        "FT_Phy_pph",
                        "FT_App_PPH",
                        "FT_PhyfirstHour",
                        "FT_AppfirstHour",
                        "PIT_Phy_pph",
                        "PIT_App_PPH",
                        "PIT_PhyfirstHour",
                        "PIT_AppFirstHour"});
            table6.AddRow(new string[] {
                        "1.5",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1"});
#line 25
 testRunner.And("Clinician Productivity tab opens enter values into fields and click on next butto" +
                    "n or click on Clinician Cost", ((string)(null)), table6, "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Average_Cost_per_Physician_Hour",
                        "Average_Cost_per_APP_Hour",
                        "Average_Cost_per_Scribe_Hour"});
            table7.AddRow(new string[] {
                        "20",
                        "60",
                        "20"});
#line 28
 testRunner.When("Clinician Cost tab opens enter vlaues into fields and click on next button or cli" +
                    "ck on Save Button", ((string)(null)), table7, "When ");
#line 32
 testRunner.Then("Model should be saved with values enter into save model popup.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
