// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DCM.Specflow.Features.Create_Model
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Create Model")]
    [NUnit.Framework.CategoryAttribute("chrome")]
    [NUnit.Framework.CategoryAttribute("SanityTest")]
    public partial class CreateModelFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "createmodel.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Create Model", "\t\tDCM login with Chrome browser and verify DCM functionality ", ProgrammingLanguage.CSharp, new string[] {
                        "chrome",
                        "SanityTest"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02 Create model with Data Benchmarking")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void _02CreateModelWithDataBenchmarking()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02 Create model with Data Benchmarking", null, new string[] {
                        "mytag"});
#line 7
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
 testRunner.Given("click on create model tab from dashboard and click on Create Model using Free For" +
                    "m from popup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Area2",
                        "Area3",
                        "Forecasted_Annual_Arrivals",
                        "Current_LWBS_rate",
                        "Admit_Percentage"});
            table4.AddRow(new string[] {
                        "FT",
                        "PIT",
                        "80000",
                        "3",
                        "12"});
#line 9
 testRunner.And("enter values into Practice Metrics fields and click on next button or click on Ar" +
                    "rivals/ESL", ((string)(null)), table4, "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "FT_ESI_3",
                        "PIT_ESI_3"});
            table5.AddRow(new string[] {
                        "20",
                        "5"});
#line 13
 testRunner.When("Arrivals/ESL tab opens enter values into fields and click on next button or click" +
                    " on Length of Stay", ((string)(null)), table5, "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Overall_Admit_LOS",
                        "Overall_Arrival_To_Admit_Decision",
                        "Main_Discharge_LOS",
                        "FT_Discharge_LOS",
                        "PIT_Discharge_LOS"});
            table6.AddRow(new string[] {
                        "120",
                        "60",
                        "90",
                        "30",
                        "30"});
#line 17
 testRunner.And("Length of Stay tab opens enter values into fields and click on next button or cli" +
                    "ck on Shifts", ((string)(null)), table6, "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "From_Time",
                        "To_Time"});
            table7.AddRow(new string[] {
                        "01Hr",
                        "08Hr"});
#line 21
 testRunner.When("Shifts tab opens enter values into fields and click on next button or click on Cl" +
                    "inician Productivity", ((string)(null)), table7, "When ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "main_phy_pph",
                        "main_app_pph",
                        "main_PhyFirstHour",
                        "main_appFirstHour",
                        "FT_Phy_pph",
                        "FT_App_PPH",
                        "FT_PhyfirstHour",
                        "FT_AppfirstHour",
                        "PIT_Phy_pph",
                        "PIT_App_PPH",
                        "PIT_PhyfirstHour",
                        "PIT_AppFirstHour"});
            table8.AddRow(new string[] {
                        "1.5",
                        "1",
                        "2",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1"});
#line 25
 testRunner.And("Clinician Productivity tab opens enter values into fields and click on next butto" +
                    "n or click on Clinician Cost", ((string)(null)), table8, "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Average_Cost_per_Physician_Hour",
                        "Average_Cost_per_APP_Hour",
                        "Average_Cost_per_Scribe_Hour"});
            table9.AddRow(new string[] {
                        "20",
                        "60",
                        "20"});
#line 28
 testRunner.When("Clinician Cost tab opens enter vlaues into fields and click on next button or cli" +
                    "ck on Save Button", ((string)(null)), table9, "When ");
#line 32
 testRunner.Then("Model should be saved with values enter into save model popup.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01 Create model with import")]
        public virtual void _01CreateModelWithImport()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 Create model with import", null, ((string[])(null)));
#line 35
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 36
 testRunner.Given("click on create model tab from dashboard and click on Create Model using Free For" +
                    "m from popup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Area2",
                        "Area3",
                        "Forecasted_Annual_Arrivals",
                        "Current_LWBS_rate",
                        "Admit_Percentage"});
            table10.AddRow(new string[] {
                        "FT",
                        "PIT",
                        "80000",
                        "3",
                        "12"});
#line 37
 testRunner.And("enter values into Practice Metrics fields and click on next button or click on Ar" +
                    "rivals/ESL", ((string)(null)), table10, "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "FT_ESI_3",
                        "PIT_ESI_3"});
            table11.AddRow(new string[] {
                        "20",
                        "5"});
#line 41
 testRunner.When("Arrivals/ESL tab opens import data and enter values into fields and click on next" +
                    " button or click on Length of Stay", ((string)(null)), table11, "When ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Overall_Admit_LOS",
                        "Overall_Arrival_To_Admit_Decision",
                        "Main_Discharge_LOS",
                        "FT_Discharge_LOS",
                        "PIT_Discharge_LOS"});
            table12.AddRow(new string[] {
                        "120",
                        "60",
                        "90",
                        "30",
                        "30"});
#line 45
 testRunner.And("Length of Stay tab opens enter values into fields and click on next button or cli" +
                    "ck on Shifts", ((string)(null)), table12, "And ");
#line 49
 testRunner.When("Shifts tab opens import values into fields and click on next button or click on C" +
                    "linician Productivity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "main_phy_pph",
                        "main_app_pph",
                        "main_PhyFirstHour",
                        "main_appFirstHour",
                        "FT_Phy_pph",
                        "FT_App_PPH",
                        "FT_PhyfirstHour",
                        "FT_AppfirstHour",
                        "PIT_Phy_pph",
                        "PIT_App_PPH",
                        "PIT_PhyfirstHour",
                        "PIT_AppFirstHour"});
            table13.AddRow(new string[] {
                        "1.5",
                        "1",
                        "2",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1"});
#line 52
 testRunner.And("Clinician Productivity tab opens enter values into fields and click on next butto" +
                    "n or click on Clinician Cost", ((string)(null)), table13, "And ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Average_Cost_per_Physician_Hour",
                        "Average_Cost_per_APP_Hour",
                        "Average_Cost_per_Scribe_Hour"});
            table14.AddRow(new string[] {
                        "20",
                        "60",
                        "20"});
#line 55
 testRunner.When("Clinician Cost tab opens enter vlaues into fields and click on next button or cli" +
                    "ck on Save Button", ((string)(null)), table14, "When ");
#line 59
 testRunner.Then("Model should be saved with values enter into save model popup.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03 Create model with Manual Entery")]
        public virtual void _03CreateModelWithManualEntery()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03 Create model with Manual Entery", null, ((string[])(null)));
#line 62
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 63
 testRunner.Given("click on create model tab from dashboard and click on Create Model using Free For" +
                    "m from popup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Area2",
                        "Area3",
                        "Forecasted_Annual_Arrivals",
                        "Current_LWBS_rate",
                        "Admit_Percentage"});
            table15.AddRow(new string[] {
                        "FT",
                        "PIT",
                        "80000",
                        "3",
                        "12"});
#line 64
 testRunner.And("enter values into Practice Metrics fields and click on next button or click on Ar" +
                    "rivals/ESL", ((string)(null)), table15, "And ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "JAN",
                        "FEB",
                        "MAR",
                        "APR",
                        "MAY",
                        "JUN",
                        "JUL",
                        "AUG",
                        "SEP",
                        "OCT",
                        "NOV",
                        "DEC"});
            table16.AddRow(new string[] {
                        "5087",
                        "4752",
                        "5336",
                        "5066",
                        "5399",
                        "5061",
                        "5227",
                        "5137",
                        "5137",
                        "4835",
                        "4856",
                        "5030"});
#line 68
 testRunner.When("Arrivals/ESL tab opens, select let me enter my own from dropdown and enter values" +
                    " into Actual Monthly Arrival fields", ((string)(null)), table16, "When ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Hr_00",
                        "Hr_01",
                        "Hr_02",
                        "Hr_03",
                        "Hr_04",
                        "Hr_05",
                        "Hr_06",
                        "Hr_07",
                        "Hr_08",
                        "Hr_09",
                        "Hr_10",
                        "Hr_11",
                        "Hr_12",
                        "Hr_13",
                        "Hr_14",
                        "Hr_15",
                        "Hr_16",
                        "Hr_17",
                        "Hr_18",
                        "Hr_19",
                        "Hr_20",
                        "Hr_21",
                        "Hr_22",
                        "Hr_23"});
            table17.AddRow(new string[] {
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1"});
#line 71
 testRunner.And("enter values into Actual Hourly Arrivals By Day Of Week for Sunday fields", ((string)(null)), table17, "And ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Hr_00",
                        "Hr_01",
                        "Hr_02",
                        "Hr_03",
                        "Hr_04",
                        "Hr_05",
                        "Hr_06",
                        "Hr_07",
                        "Hr_08",
                        "Hr_09",
                        "Hr_10",
                        "Hr_11",
                        "Hr_12",
                        "Hr_13",
                        "Hr_14",
                        "Hr_15",
                        "Hr_16",
                        "Hr_17",
                        "Hr_18",
                        "Hr_19",
                        "Hr_20",
                        "Hr_21",
                        "Hr_22",
                        "Hr_23"});
            table18.AddRow(new string[] {
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1"});
#line 74
 testRunner.And("enter values into Actual Hourly Arrivals By Day Of Week for Monday fields", ((string)(null)), table18, "And ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Hr_00",
                        "Hr_01",
                        "Hr_02",
                        "Hr_03",
                        "Hr_04",
                        "Hr_05",
                        "Hr_06",
                        "Hr_07",
                        "Hr_08",
                        "Hr_09",
                        "Hr_10",
                        "Hr_11",
                        "Hr_12",
                        "Hr_13",
                        "Hr_14",
                        "Hr_15",
                        "Hr_16",
                        "Hr_17",
                        "Hr_18",
                        "Hr_19",
                        "Hr_20",
                        "Hr_21",
                        "Hr_22",
                        "Hr_23"});
            table19.AddRow(new string[] {
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1"});
#line 77
 testRunner.And("enter values into Actual Hourly Arrivals By Day Of Week for Tuesday fields", ((string)(null)), table19, "And ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Hr_00",
                        "Hr_01",
                        "Hr_02",
                        "Hr_03",
                        "Hr_04",
                        "Hr_05",
                        "Hr_06",
                        "Hr_07",
                        "Hr_08",
                        "Hr_09",
                        "Hr_10",
                        "Hr_11",
                        "Hr_12",
                        "Hr_13",
                        "Hr_14",
                        "Hr_15",
                        "Hr_16",
                        "Hr_17",
                        "Hr_18",
                        "Hr_19",
                        "Hr_20",
                        "Hr_21",
                        "Hr_22",
                        "Hr_23"});
            table20.AddRow(new string[] {
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1"});
#line 80
 testRunner.And("enter values into Actual Hourly Arrivals By Day Of Week for Wednesday fields", ((string)(null)), table20, "And ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Hr_00",
                        "Hr_01",
                        "Hr_02",
                        "Hr_03",
                        "Hr_04",
                        "Hr_05",
                        "Hr_06",
                        "Hr_07",
                        "Hr_08",
                        "Hr_09",
                        "Hr_10",
                        "Hr_11",
                        "Hr_12",
                        "Hr_13",
                        "Hr_14",
                        "Hr_15",
                        "Hr_16",
                        "Hr_17",
                        "Hr_18",
                        "Hr_19",
                        "Hr_20",
                        "Hr_21",
                        "Hr_22",
                        "Hr_23"});
            table21.AddRow(new string[] {
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1"});
#line 83
 testRunner.And("enter values into Actual Hourly Arrivals By Day Of Week for Thursday fields", ((string)(null)), table21, "And ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Hr_00",
                        "Hr_01",
                        "Hr_02",
                        "Hr_03",
                        "Hr_04",
                        "Hr_05",
                        "Hr_06",
                        "Hr_07",
                        "Hr_08",
                        "Hr_09",
                        "Hr_10",
                        "Hr_11",
                        "Hr_12",
                        "Hr_13",
                        "Hr_14",
                        "Hr_15",
                        "Hr_16",
                        "Hr_17",
                        "Hr_18",
                        "Hr_19",
                        "Hr_20",
                        "Hr_21",
                        "Hr_22",
                        "Hr_23"});
            table22.AddRow(new string[] {
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1"});
#line 86
 testRunner.And("enter values into Actual Hourly Arrivals By Day Of Week for Friday fields", ((string)(null)), table22, "And ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Hr_00",
                        "Hr_01",
                        "Hr_02",
                        "Hr_03",
                        "Hr_04",
                        "Hr_05",
                        "Hr_06",
                        "Hr_07",
                        "Hr_08",
                        "Hr_09",
                        "Hr_10",
                        "Hr_11",
                        "Hr_12",
                        "Hr_13",
                        "Hr_14",
                        "Hr_15",
                        "Hr_16",
                        "Hr_17",
                        "Hr_18",
                        "Hr_19",
                        "Hr_20",
                        "Hr_21",
                        "Hr_22",
                        "Hr_23"});
            table23.AddRow(new string[] {
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1"});
#line 89
 testRunner.And("enter values into Actual Hourly Arrivals By Day Of Week for Saturday fields", ((string)(null)), table23, "And ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "ESI1",
                        "ESI2",
                        "ESI3",
                        "ESI4"});
            table24.AddRow(new string[] {
                        "10",
                        "10",
                        "10",
                        "10"});
#line 93
 testRunner.When("select let me enter my own from dropdown and enter values into Segmentation by ES" +
                    "I Levels fields", ((string)(null)), table24, "When ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "ESI1",
                        "ESI2",
                        "ESI3",
                        "ESI4",
                        "ESI5"});
            table25.AddRow(new string[] {
                        "10",
                        "10",
                        "10",
                        "10",
                        "10"});
#line 96
 testRunner.And("enter values into Area1 fields", ((string)(null)), table25, "And ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "ESI1",
                        "ESI2",
                        "ESI3",
                        "ESI4",
                        "ESI5"});
            table26.AddRow(new string[] {
                        "10",
                        "10",
                        "10",
                        "10",
                        "10"});
#line 99
 testRunner.And("enter values into Area2 fields and click on next button", ((string)(null)), table26, "And ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Overall_Admit_LOS",
                        "Overall_Arrival_To_Admit_Decision",
                        "Main_Discharge_LOS",
                        "FT_Discharge_LOS",
                        "PIT_Discharge_LOS"});
            table27.AddRow(new string[] {
                        "120",
                        "60",
                        "90",
                        "30",
                        "30"});
#line 103
 testRunner.And("Length of Stay tab opens enter values into fields and click on next button or cli" +
                    "ck on Shifts", ((string)(null)), table27, "And ");
#line 107
 testRunner.When("Shifts tab opens import values into fields and click on next button or click on C" +
                    "linician Productivity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "main_phy_pph",
                        "main_app_pph",
                        "main_PhyFirstHour",
                        "main_appFirstHour",
                        "FT_Phy_pph",
                        "FT_App_PPH",
                        "FT_PhyfirstHour",
                        "FT_AppfirstHour",
                        "PIT_Phy_pph",
                        "PIT_App_PPH",
                        "PIT_PhyfirstHour",
                        "PIT_AppFirstHour"});
            table28.AddRow(new string[] {
                        "1.5",
                        "1",
                        "2",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1"});
#line 110
 testRunner.And("Clinician Productivity tab opens enter values into fields and click on next butto" +
                    "n or click on Clinician Cost", ((string)(null)), table28, "And ");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "Average_Cost_per_Physician_Hour",
                        "Average_Cost_per_APP_Hour",
                        "Average_Cost_per_Scribe_Hour"});
            table29.AddRow(new string[] {
                        "20",
                        "60",
                        "20"});
#line 113
 testRunner.When("Clinician Cost tab opens enter vlaues into fields and click on next button or cli" +
                    "ck on Save Button", ((string)(null)), table29, "When ");
#line 117
 testRunner.Then("Model should be saved with values enter into save model popup.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
