// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DCM.Specflow.Features.Za_DirectLink_To_Model
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Verify DirectLink to model for DCM users")]
    [NUnit.Framework.CategoryAttribute("chrome")]
    public partial class VerifyDirectLinkToModelForDCMUsersFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "VerifyDirectLinkforDCMusers.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Verify DirectLink to model for DCM users", "\t\tVerify with Full access and Viewer role", ProgrammingLanguage.CSharp, new string[] {
                        "chrome"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01 Verify direct link to edit input tab of other\'s private model")]
        [NUnit.Framework.CategoryAttribute("Task:46137")]
        public virtual void _01VerifyDirectLinkToEditInputTabOfOthersPrivateModel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 Verify direct link to edit input tab of other\'s private model", null, new string[] {
                        "Task:46137"});
#line 6
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 7
 testRunner.Given("verify current URL", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table119 = new TechTalk.SpecFlow.Table(new string[] {
                        "link"});
            table119.AddRow(new string[] {
                        "https://dcmqa.evhc.net/v2/input?modelId=4258"});
#line 8
 testRunner.And("Click on below link and login to open edit input tab of other\'s private model", ((string)(null)), table119, "And ");
#line 12
 testRunner.Then("Verify edit input tab And logout from DCM and Okta.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02 Verify direct link to View Analysis tab of other\'s private model")]
        public virtual void _02VerifyDirectLinkToViewAnalysisTabOfOthersPrivateModel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02 Verify direct link to View Analysis tab of other\'s private model", null, ((string[])(null)));
#line 14
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 15
 testRunner.Given("verify current URL", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table120 = new TechTalk.SpecFlow.Table(new string[] {
                        "link"});
            table120.AddRow(new string[] {
                        "https://dcmqa.evhc.net/v2/analysis?modelId=4295"});
#line 16
 testRunner.And("Click on below link and login to open View Analysis tab of other\'s private model", ((string)(null)), table120, "And ");
#line 20
 testRunner.Then("Verify edit input tab And logout from DCM and Okta.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03 Verify direct link to Sensitivity Analysis tab of other\'s private model")]
        public virtual void _03VerifyDirectLinkToSensitivityAnalysisTabOfOthersPrivateModel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03 Verify direct link to Sensitivity Analysis tab of other\'s private model", null, ((string[])(null)));
#line 22
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 23
 testRunner.Given("verify current URL", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table121 = new TechTalk.SpecFlow.Table(new string[] {
                        "link"});
            table121.AddRow(new string[] {
                        "https://dcmqa.evhc.net/v2/sensitivityanalysis?modelId=4258"});
#line 24
 testRunner.And("Click on below link and login to open Sensitivity Analysis tab of other\'s private" +
                    " model", ((string)(null)), table121, "And ");
#line 28
 testRunner.Then("Verify edit input tab And logout from DCM and Okta.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("04 Verify direct link to Executive Summary tab of other\'s private model")]
        public virtual void _04VerifyDirectLinkToExecutiveSummaryTabOfOthersPrivateModel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("04 Verify direct link to Executive Summary tab of other\'s private model", null, ((string[])(null)));
#line 30
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 31
 testRunner.Given("verify current URL", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table122 = new TechTalk.SpecFlow.Table(new string[] {
                        "link"});
            table122.AddRow(new string[] {
                        "https://dcmqa.evhc.net/v2/executivesummary?modelId=4258"});
#line 32
 testRunner.And("Click on below link and login to open Executive Summary tab of other\'s private mo" +
                    "del", ((string)(null)), table122, "And ");
#line 36
 testRunner.Then("Verify edit input tab And logout from DCM and Okta.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("05 Verify direct link to edit input tab using Viewer role")]
        [NUnit.Framework.CategoryAttribute("viewer_role")]
        public virtual void _05VerifyDirectLinkToEditInputTabUsingViewerRole()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("05 Verify direct link to edit input tab using Viewer role", null, new string[] {
                        "viewer_role"});
#line 42
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 43
 testRunner.Given("verify current URL", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table123 = new TechTalk.SpecFlow.Table(new string[] {
                        "link"});
            table123.AddRow(new string[] {
                        "https://dcmqa.evhc.net/v2/input?modelId=4258"});
#line 44
 testRunner.And("Click on below link and login to open edit input tab using Viewer role", ((string)(null)), table123, "And ");
#line 48
 testRunner.Then("Verify edit input tab And logout from DCM and Okta.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("06 Verify direct link to View Analysis tab using Viewer role")]
        public virtual void _06VerifyDirectLinkToViewAnalysisTabUsingViewerRole()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("06 Verify direct link to View Analysis tab using Viewer role", null, ((string[])(null)));
#line 50
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 51
 testRunner.Given("verify current URL", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table124 = new TechTalk.SpecFlow.Table(new string[] {
                        "link"});
            table124.AddRow(new string[] {
                        "https://dcmqa.evhc.net/v2/analysis?modelId=4295"});
#line 52
 testRunner.And("Click on below link and login to open View Analysis tab using Viewer role", ((string)(null)), table124, "And ");
#line 56
 testRunner.Then("Verify edit input tab And logout from DCM and Okta.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("07 Verify direct link to Sensitivity Analysis tab using Viewer role")]
        public virtual void _07VerifyDirectLinkToSensitivityAnalysisTabUsingViewerRole()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("07 Verify direct link to Sensitivity Analysis tab using Viewer role", null, ((string[])(null)));
#line 58
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 59
 testRunner.Given("verify current URL", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table125 = new TechTalk.SpecFlow.Table(new string[] {
                        "link"});
            table125.AddRow(new string[] {
                        "https://dcmqa.evhc.net/v2/sensitivityanalysis?modelId=4258"});
#line 60
 testRunner.And("Click on below link and login to open Sensitivity Analysis tab using Viewer role", ((string)(null)), table125, "And ");
#line 64
 testRunner.Then("Verify edit input tab And logout from DCM and Okta.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("08 Verify direct link to Executive Summary tab using Viewer role")]
        public virtual void _08VerifyDirectLinkToExecutiveSummaryTabUsingViewerRole()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("08 Verify direct link to Executive Summary tab using Viewer role", null, ((string[])(null)));
#line 66
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 67
 testRunner.Given("verify current URL", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table126 = new TechTalk.SpecFlow.Table(new string[] {
                        "link"});
            table126.AddRow(new string[] {
                        "https://dcmqa.evhc.net/v2/executivesummary?modelId=4258"});
#line 68
 testRunner.And("Click on below link and login to open Executive Summary tab using Viewer role", ((string)(null)), table126, "And ");
#line 72
 testRunner.Then("Verify edit input tab And logout from DCM and Okta.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
