// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DCM.Specflow.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("CreateModelwithWizard")]
    [NUnit.Framework.CategoryAttribute("chrome")]
    [NUnit.Framework.CategoryAttribute("SanityTest")]
    public partial class CreateModelwithWizardFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CreateModelwithWizard.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CreateModelwithWizard", "\tDCM login with Chrome browser and Create model using Wizard", ProgrammingLanguage.CSharp, new string[] {
                        "chrome",
                        "SanityTest"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01")]
        public virtual void _01()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01", null, ((string[])(null)));
#line 7
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
 testRunner.Given("click on create model tab from dashboard and click on Create Model using Wizard f" +
                    "rom popup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "FAA_Wizard"});
            table1.AddRow(new string[] {
                        "80000"});
#line 9
 testRunner.And("enter value into What is the Forecasted Annual Arrivals (walkouts included) of yo" +
                    "ur Emergency Department? question and hit hit enter", ((string)(null)), table1, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Current_Walkout_Percentage"});
            table2.AddRow(new string[] {
                        "3"});
#line 13
 testRunner.When("What\'s your current walkout (Left without Triage or Left without being seen) perc" +
                    "entage? question appeared then enter the value in textbox and hit enter", ((string)(null)), table2, "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Admitted_patients_percentage"});
            table3.AddRow(new string[] {
                        "20"});
#line 19
 testRunner.And("What percentage of patients get admitted?  question appeared then enter the value" +
                    " in text box and hit enter", ((string)(null)), table3, "And ");
#line 23
 testRunner.When(@"How many patients come to your Emergency Department each month? Each hour during the week? question appeared and click on Apply Data Benchmarking Average pattern and Arrivals pop up will get appeared then click on OK button and verify the Click to view Arrival link appeared", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 25
 testRunner.When("What is the Emergency Severity Index (ESI) breakdown for your Emergency Departmen" +
                    "t?  then click on  Apply Data Benchmarking Average pattern  and ESI pop up displ" +
                    "ayed then click on OK button after click on OK verify  Click to view ESI  link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Los_for_Addmitted_patients"});
            table4.AddRow(new string[] {
                        "147"});
#line 27
 testRunner.When("What is the Length of Stay (in minutes) for Admitted patients in your Emergency D" +
                    "epartment?  question appeared, enter the value in textbox and press enter", ((string)(null)), table4, "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Los_for_Discharged_patients"});
            table5.AddRow(new string[] {
                        "200"});
#line 31
 testRunner.When("What is the Length of Stay (in minutes) for Discharged patients in your Emergency" +
                    " Department? question appeared enter the value in textbox and press enter", ((string)(null)), table5, "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Arrival_to_admit_decision_time"});
            table6.AddRow(new string[] {
                        "150"});
#line 36
 testRunner.When("What is your Arrival to Admit Decision time (in minutes)?  question appeared, ent" +
                    "er the value in textbox and press enter", ((string)(null)), table6, "When ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Duplicate_Shifts",
                        "Current_To_Time",
                        "Proposed_From_Time",
                        "Proposed_To_Time"});
            table7.AddRow(new string[] {
                        "2",
                        "18",
                        "05",
                        "19"});
#line 41
 testRunner.When("What is your typical staffing pattern? appeared, click on  I\'d like to enter the " +
                    "data manually and Shifts pop up displayed then add shifts manually and click on " +
                    "OK to close pop up", ((string)(null)), table7, "When ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phy_cost"});
            table8.AddRow(new string[] {
                        "350"});
#line 47
 testRunner.When("What is your average cost (in dollars) per Physician hours? Please enter 0 in cas" +
                    "e of no cost.  question appeared, enter the value in textbox and press enter", ((string)(null)), table8, "When ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "APP_cost"});
            table9.AddRow(new string[] {
                        "300"});
#line 52
 testRunner.When("If you use Advanced Practice Providers (APPs), what is your average cost (in doll" +
                    "ars) per APP hours? Please enter 0 in case of no cost.  question appeared, enter" +
                    " the value in textbox and press enter", ((string)(null)), table9, "When ");
#line 57
 testRunner.When("We have defaulted your average cost (in dollars) per Scribe hours to $20. Do you " +
                    "want to change?  question appeared then click on  No, I want to continue with th" +
                    "e default average cost per Scribe hours.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Targeted_Phy_PPH"});
            table10.AddRow(new string[] {
                        "2.5"});
#line 59
 testRunner.When("How many patients does your Physicians see per hour (PPH)?  question appeared, en" +
                    "ter the value in textbox and press enter", ((string)(null)), table10, "When ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Targeted_APP_PPH"});
            table11.AddRow(new string[] {
                        "1.25"});
#line 64
 testRunner.When("How many patients does your APPs see per hour (PPH)?  question appeared, enter th" +
                    "e value in textbox and press enter and verify the  Your APP coefficient calculat" +
                    "es to  value", ((string)(null)), table11, "When ");
#line 69
 testRunner.When("We have defaulted your Scribe coefficient (efficiency of providers Scribes increa" +
                    "se in percent) to 15%. Do you want to change?  question appeared then click on  " +
                    "No, I want to continue with the default Scribe coefficient.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phy_First_hour"});
            table12.AddRow(new string[] {
                        "3"});
#line 71
 testRunner.When("Do your Physicians have a higher than average PPH during their first hour of the " +
                    "work? If YES, please enter the PPH during the first hour. If NO, please enter 0." +
                    "  question appeared, enter the value in textbox and press enter", ((string)(null)), table12, "When ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "APP_First_hour"});
            table13.AddRow(new string[] {
                        "2"});
#line 76
 testRunner.When("Do your APPs have a higher than average PPH during their first hour of the work? " +
                    "If YES, please enter the PPH during the first hour. If NO, please enter 0.  ques" +
                    "tion appeared, enter the value in textbox and press enter", ((string)(null)), table13, "When ");
#line 81
 testRunner.When("Are there any other areas in your Emergency Department?  question appeared then c" +
                    "lick on  NO that\'s all", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 83
 testRunner.And("Clinical Work Distribution for Patient Encounters  pop up displayed then click on" +
                    " OK button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 85
 testRunner.When("Save Model  pop up displayed then enter mandatory information and click on Save", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 87
 testRunner.Then("model should get created and success message should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
