// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DCM.Specflow.Features.Wizard
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("CreateModelwithWizard")]
    [NUnit.Framework.CategoryAttribute("chrome")]
    [NUnit.Framework.CategoryAttribute("SanityTest")]
    public partial class CreateModelwithWizardFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CreateModelwithWizard.feature.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CreateModelwithWizard", "\tDCM login with Chrome browser and Create model using Wizard", ProgrammingLanguage.CSharp, new string[] {
                        "chrome",
                        "SanityTest"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("01 Create Wizard model using data Benchmarking")]
        public virtual void _01CreateWizardModelUsingDataBenchmarking()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("01 Create Wizard model using data Benchmarking", null, ((string[])(null)));
#line 7
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
 testRunner.Given("click on create model tab from dashboard and click on Create Model using Wizard f" +
                    "rom popup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "FAA_Wizard"});
            table38.AddRow(new string[] {
                        "80000"});
#line 9
 testRunner.And("enter value into What is the Forecasted Annual Arrivals (walkouts included) of yo" +
                    "ur Emergency Department? question and hit hit enter", ((string)(null)), table38, "And ");
#line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "Current_Walkout_Percentage"});
            table39.AddRow(new string[] {
                        "3"});
#line 13
 testRunner.When("What\'s your current walkout (Left without Triage or Left without being seen) perc" +
                    "entage? question appeared then enter the value in textbox and hit enter And veri" +
                    "fy Your Forecasted Annual Volume", ((string)(null)), table39, "When ");
#line hidden
            TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                        "Admitted_patients_percentage"});
            table40.AddRow(new string[] {
                        "20"});
#line 17
 testRunner.And("What percentage of patients get admitted?  question appeared then enter the value" +
                    " in text box and hit enter", ((string)(null)), table40, "And ");
#line 21
 testRunner.When(@"How many patients come to your Emergency Department each month? Each hour during the week? question appeared and click on Apply Data Benchmarking Average pattern and Arrivals pop up will get appeared then click on OK button and verify the Click to view Arrival link appeared", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 23
 testRunner.When("What is the Emergency Severity Index (ESI) breakdown for your Emergency Departmen" +
                    "t?  then click on  Apply Data Benchmarking Average pattern  and ESI pop up displ" +
                    "ayed then click on OK button after click on OK verify  Click to view ESI  link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                        "Los_for_Addmitted_patients"});
            table41.AddRow(new string[] {
                        "147"});
#line 25
 testRunner.When("What is the Length of Stay (in minutes) for Admitted patients in your Emergency D" +
                    "epartment?  question appeared, enter the value in textbox and press enter", ((string)(null)), table41, "When ");
#line hidden
            TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                        "Los_for_Discharged_patients"});
            table42.AddRow(new string[] {
                        "200"});
#line 29
 testRunner.When("What is the Length of Stay (in minutes) for Discharged patients in your Emergency" +
                    " Department? question appeared enter the value in textbox and press enter", ((string)(null)), table42, "When ");
#line hidden
            TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                        "Arrival_to_admit_decision_time"});
            table43.AddRow(new string[] {
                        "150"});
#line 34
 testRunner.When("What is your Arrival to Admit Decision time (in minutes)?  question appeared, ent" +
                    "er the value in textbox and press enter", ((string)(null)), table43, "When ");
#line hidden
            TechTalk.SpecFlow.Table table44 = new TechTalk.SpecFlow.Table(new string[] {
                        "Duplicate_Shifts",
                        "Current_To_Time",
                        "Proposed_From_Time",
                        "Proposed_To_Time"});
            table44.AddRow(new string[] {
                        "2",
                        "18",
                        "05",
                        "19"});
#line 39
 testRunner.When("What is your typical staffing pattern? appeared, click on  I\'d like to enter the " +
                    "data manually and Shifts pop up displayed then add shifts manually and click on " +
                    "OK to close pop up", ((string)(null)), table44, "When ");
#line hidden
            TechTalk.SpecFlow.Table table45 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phy_cost"});
            table45.AddRow(new string[] {
                        "350"});
#line 45
 testRunner.When("What is your average cost (in dollars) per Physician hours? Please enter 0 in cas" +
                    "e of no cost.  question appeared, enter the value in textbox and press enter", ((string)(null)), table45, "When ");
#line hidden
            TechTalk.SpecFlow.Table table46 = new TechTalk.SpecFlow.Table(new string[] {
                        "APP_cost"});
            table46.AddRow(new string[] {
                        "300"});
#line 50
 testRunner.When("If you use Advanced Practice Providers (APPs), what is your average cost (in doll" +
                    "ars) per APP hours? Please enter 0 in case of no cost.  question appeared, enter" +
                    " the value in textbox and press enter", ((string)(null)), table46, "When ");
#line 55
 testRunner.When("We have defaulted your average cost (in dollars) per Scribe hours to $20. Do you " +
                    "want to change?  question appeared then click on  No, I want to continue with th" +
                    "e default average cost per Scribe hours.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table47 = new TechTalk.SpecFlow.Table(new string[] {
                        "Targeted_Phy_PPH"});
            table47.AddRow(new string[] {
                        "2.5"});
#line 57
 testRunner.When("How many patients does your Physicians see per hour (PPH)?  question appeared, en" +
                    "ter the value in textbox and press enter", ((string)(null)), table47, "When ");
#line hidden
            TechTalk.SpecFlow.Table table48 = new TechTalk.SpecFlow.Table(new string[] {
                        "Targeted_APP_PPH"});
            table48.AddRow(new string[] {
                        "1.25"});
#line 62
 testRunner.When("How many patients does your APPs see per hour (PPH)?  question appeared, enter th" +
                    "e value in textbox and press enter and verify the  Your APP coefficient calculat" +
                    "es to  value", ((string)(null)), table48, "When ");
#line 67
 testRunner.When("We have defaulted your Scribe coefficient (efficiency of providers Scribes increa" +
                    "se in percent) to 15%. Do you want to change?  question appeared then click on  " +
                    "No, I want to continue with the default Scribe coefficient.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table49 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phy_First_hour"});
            table49.AddRow(new string[] {
                        "3"});
#line 69
 testRunner.When("Do your Physicians have a higher than average PPH during their first hour of the " +
                    "work? If YES, please enter the PPH during the first hour. If NO, please enter 0." +
                    "  question appeared, enter the value in textbox and press enter", ((string)(null)), table49, "When ");
#line hidden
            TechTalk.SpecFlow.Table table50 = new TechTalk.SpecFlow.Table(new string[] {
                        "APP_First_hour"});
            table50.AddRow(new string[] {
                        "2"});
#line 74
 testRunner.When("Do your APPs have a higher than average PPH during their first hour of the work? " +
                    "If YES, please enter the PPH during the first hour. If NO, please enter 0.  ques" +
                    "tion appeared, enter the value in textbox and press enter", ((string)(null)), table50, "When ");
#line 79
 testRunner.When("Are there any other areas in your Emergency Department?  question appeared then c" +
                    "lick on  NO that\'s all", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 81
 testRunner.And("Clinical Work Distribution for Patient Encounters  pop up displayed then click on" +
                    " OK button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 83
 testRunner.When("Save Model  pop up displayed then enter mandatory information and click on Save", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 85
 testRunner.Then("model should get created and success message should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("02 Create Wizard model using Import data and manual ESI entry")]
        public virtual void _02CreateWizardModelUsingImportDataAndManualESIEntry()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("02 Create Wizard model using Import data and manual ESI entry", null, ((string[])(null)));
#line 89
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 91
 testRunner.Given("click on create model tab from dashboard and click on Create Model using Wizard f" +
                    "rom popup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table51 = new TechTalk.SpecFlow.Table(new string[] {
                        "FAA_Wizard"});
            table51.AddRow(new string[] {
                        "50000"});
#line 92
 testRunner.And("enter value into What is the Forecasted Annual Arrivals (walkouts included) of yo" +
                    "ur Emergency Department? question and hit hit enter", ((string)(null)), table51, "And ");
#line hidden
            TechTalk.SpecFlow.Table table52 = new TechTalk.SpecFlow.Table(new string[] {
                        "Current_Walkout_Percentage"});
            table52.AddRow(new string[] {
                        "3"});
#line 96
 testRunner.When("What\'s your current walkout (Left without Triage or Left without being seen) perc" +
                    "entage? question appeared then enter the value in textbox and hit enter And veri" +
                    "fy Your Forecasted Annual Volume", ((string)(null)), table52, "When ");
#line hidden
            TechTalk.SpecFlow.Table table53 = new TechTalk.SpecFlow.Table(new string[] {
                        "Admitted_patients_percentage"});
            table53.AddRow(new string[] {
                        "20"});
#line 101
 testRunner.And("What percentage of patients get admitted?  question appeared then enter the value" +
                    " in text box and hit enter", ((string)(null)), table53, "And ");
#line 105
 testRunner.When("Monthly/hourly arrivals question displayed then do import data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table54 = new TechTalk.SpecFlow.Table(new string[] {
                        "ESI1",
                        "ESI2",
                        "ESI 3",
                        "ESI 4"});
            table54.AddRow(new string[] {
                        "1",
                        "8",
                        "55",
                        "28"});
#line 107
 testRunner.When("What is the Emergency Severity Index (ESI) breakdown for your Emergency Departmen" +
                    "t?  then click on  I\'d like to enter the data manually  and ESI pop up displayed" +
                    " then  enter esi values click on OK button after click on OK verify  Click to vi" +
                    "ew ESI  link", ((string)(null)), table54, "When ");
#line hidden
            TechTalk.SpecFlow.Table table55 = new TechTalk.SpecFlow.Table(new string[] {
                        "Los_for_Addmitted_patients"});
            table55.AddRow(new string[] {
                        "147"});
#line 111
 testRunner.When("What is the Length of Stay (in minutes) for Admitted patients in your Emergency D" +
                    "epartment?  question appeared, enter the value in textbox and press enter", ((string)(null)), table55, "When ");
#line hidden
            TechTalk.SpecFlow.Table table56 = new TechTalk.SpecFlow.Table(new string[] {
                        "Los_for_Discharged_patients"});
            table56.AddRow(new string[] {
                        "200"});
#line 115
 testRunner.When("What is the Length of Stay (in minutes) for Discharged patients in your Emergency" +
                    " Department? question appeared enter the value in textbox and press enter", ((string)(null)), table56, "When ");
#line hidden
            TechTalk.SpecFlow.Table table57 = new TechTalk.SpecFlow.Table(new string[] {
                        "Arrival_to_admit_decision_time"});
            table57.AddRow(new string[] {
                        "150"});
#line 120
 testRunner.When("What is your Arrival to Admit Decision time (in minutes)?  question appeared, ent" +
                    "er the value in textbox and press enter", ((string)(null)), table57, "When ");
#line 125
 testRunner.When("Shifts questions displayed then do import shifts", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table58 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phy_cost"});
            table58.AddRow(new string[] {
                        "350"});
#line 127
 testRunner.When("What is your average cost (in dollars) per Physician hours? Please enter 0 in cas" +
                    "e of no cost.  question appeared, enter the value in textbox and press enter", ((string)(null)), table58, "When ");
#line hidden
            TechTalk.SpecFlow.Table table59 = new TechTalk.SpecFlow.Table(new string[] {
                        "APP_cost"});
            table59.AddRow(new string[] {
                        "300"});
#line 132
 testRunner.When("If you use Advanced Practice Providers (APPs), what is your average cost (in doll" +
                    "ars) per APP hours? Please enter 0 in case of no cost.  question appeared, enter" +
                    " the value in textbox and press enter", ((string)(null)), table59, "When ");
#line 137
 testRunner.When("We have defaulted your average cost (in dollars) per Scribe hours to $20. Do you " +
                    "want to change?  question appeared then click on  No, I want to continue with th" +
                    "e default average cost per Scribe hours.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table60 = new TechTalk.SpecFlow.Table(new string[] {
                        "Targeted_Phy_PPH"});
            table60.AddRow(new string[] {
                        "2.5"});
#line 139
 testRunner.When("How many patients does your Physicians see per hour (PPH)?  question appeared, en" +
                    "ter the value in textbox and press enter", ((string)(null)), table60, "When ");
#line hidden
            TechTalk.SpecFlow.Table table61 = new TechTalk.SpecFlow.Table(new string[] {
                        "Targeted_APP_PPH"});
            table61.AddRow(new string[] {
                        "1.25"});
#line 144
 testRunner.When("How many patients does your APPs see per hour (PPH)?  question appeared, enter th" +
                    "e value in textbox and press enter and verify the  Your APP coefficient calculat" +
                    "es to  value", ((string)(null)), table61, "When ");
#line 149
 testRunner.When("We have defaulted your Scribe coefficient (efficiency of providers Scribes increa" +
                    "se in percent) to 15%. Do you want to change?  question appeared then click on  " +
                    "No, I want to continue with the default Scribe coefficient.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table62 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phy_First_hour"});
            table62.AddRow(new string[] {
                        "3"});
#line 151
 testRunner.When("Do your Physicians have a higher than average PPH during their first hour of the " +
                    "work? If YES, please enter the PPH during the first hour. If NO, please enter 0." +
                    "  question appeared, enter the value in textbox and press enter", ((string)(null)), table62, "When ");
#line hidden
            TechTalk.SpecFlow.Table table63 = new TechTalk.SpecFlow.Table(new string[] {
                        "APP_First_hour"});
            table63.AddRow(new string[] {
                        "2"});
#line 156
 testRunner.When("Do your APPs have a higher than average PPH during their first hour of the work? " +
                    "If YES, please enter the PPH during the first hour. If NO, please enter 0.  ques" +
                    "tion appeared, enter the value in textbox and press enter", ((string)(null)), table63, "When ");
#line hidden
            TechTalk.SpecFlow.Table table64 = new TechTalk.SpecFlow.Table(new string[] {
                        "FTHoursFrom",
                        "FTHoursTo",
                        "FT_LOS",
                        "FT_PHY_PPH",
                        "FT_APP_PPH",
                        "FTesi3",
                        "FTLOS",
                        "FTPHYFH",
                        "FTAPPFH",
                        "Duplicate_Shifts",
                        "Current_To_Time",
                        "Proposed_From_Time",
                        "Proposed_To_Time"});
            table64.AddRow(new string[] {
                        "09:00",
                        "21:00",
                        "90",
                        "3.25",
                        "2.75",
                        "5",
                        "90",
                        "4",
                        "3",
                        "2",
                        "18",
                        "05",
                        "19"});
#line 161
 testRunner.When("Are there any other areas in your Emergency Department?  question appeared then c" +
                    "lick on  Fast track and answer all the questions", ((string)(null)), table64, "When ");
#line 166
 testRunner.And("click on No,That\'s All button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 168
 testRunner.And("Clinical Work Distribution for Patient Encounters  pop up displayed then click on" +
                    " OK button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 170
 testRunner.When("Save Model  pop up displayed then enter mandatory information and click on Save", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 172
 testRunner.Then("model should get created and success message should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("03 Cretae model with Manual arrivals data")]
        public virtual void _03CretaeModelWithManualArrivalsData()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("03 Cretae model with Manual arrivals data", null, ((string[])(null)));
#line 176
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 178
 testRunner.Given("click on create model tab from dashboard and click on Create Model using Wizard f" +
                    "rom popup", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table65 = new TechTalk.SpecFlow.Table(new string[] {
                        "FAA_Wizard"});
            table65.AddRow(new string[] {
                        "50000"});
#line 179
 testRunner.And("enter value into What is the Forecasted Annual Arrivals (walkouts included) of yo" +
                    "ur Emergency Department? question and hit hit enter", ((string)(null)), table65, "And ");
#line hidden
            TechTalk.SpecFlow.Table table66 = new TechTalk.SpecFlow.Table(new string[] {
                        "Current_Walkout_Percentage"});
            table66.AddRow(new string[] {
                        "3"});
#line 183
 testRunner.When("What\'s your current walkout (Left without Triage or Left without being seen) perc" +
                    "entage? question appeared then enter the value in textbox and hit enter And veri" +
                    "fy Your Forecasted Annual Volume", ((string)(null)), table66, "When ");
#line hidden
            TechTalk.SpecFlow.Table table67 = new TechTalk.SpecFlow.Table(new string[] {
                        "Admitted_patients_percentage"});
            table67.AddRow(new string[] {
                        "20"});
#line 188
 testRunner.And("What percentage of patients get admitted?  question appeared then enter the value" +
                    " in text box and hit enter", ((string)(null)), table67, "And ");
#line hidden
            TechTalk.SpecFlow.Table table68 = new TechTalk.SpecFlow.Table(new string[] {
                        "JAN",
                        "FEB",
                        "MAR",
                        "APR",
                        "MAY",
                        "JUN",
                        "JUL",
                        "AUG",
                        "SEP",
                        "OCT",
                        "NOV",
                        "DEC"});
            table68.AddRow(new string[] {
                        "5087",
                        "4752",
                        "5336",
                        "5066",
                        "5399",
                        "5061",
                        "5227",
                        "5137",
                        "5137",
                        "4835",
                        "4856",
                        "5030"});
#line 193
 testRunner.When("Arrivals question displayed then click on Enter data manually and enter monthly d" +
                    "ata", ((string)(null)), table68, "When ");
#line hidden
            TechTalk.SpecFlow.Table table69 = new TechTalk.SpecFlow.Table(new string[] {
                        "Hr_00",
                        "Hr_01",
                        "Hr_02",
                        "Hr_03",
                        "Hr_04",
                        "Hr_05",
                        "Hr_06",
                        "Hr_07",
                        "Hr_08",
                        "Hr_09",
                        "Hr_10",
                        "Hr_11",
                        "Hr_12",
                        "Hr_13",
                        "Hr_14",
                        "Hr_15",
                        "Hr_16",
                        "Hr_17",
                        "Hr_18",
                        "Hr_19",
                        "Hr_20",
                        "Hr_21",
                        "Hr_22",
                        "Hr_23"});
            table69.AddRow(new string[] {
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1"});
#line 196
 testRunner.And("enter values into Actual Hourly Arrivals By Day Of Week for Sunday fields", ((string)(null)), table69, "And ");
#line hidden
            TechTalk.SpecFlow.Table table70 = new TechTalk.SpecFlow.Table(new string[] {
                        "Hr_00",
                        "Hr_01",
                        "Hr_02",
                        "Hr_03",
                        "Hr_04",
                        "Hr_05",
                        "Hr_06",
                        "Hr_07",
                        "Hr_08",
                        "Hr_09",
                        "Hr_10",
                        "Hr_11",
                        "Hr_12",
                        "Hr_13",
                        "Hr_14",
                        "Hr_15",
                        "Hr_16",
                        "Hr_17",
                        "Hr_18",
                        "Hr_19",
                        "Hr_20",
                        "Hr_21",
                        "Hr_22",
                        "Hr_23"});
            table70.AddRow(new string[] {
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1"});
#line 199
 testRunner.And("enter values into Actual Hourly Arrivals By Day Of Week for Monday fields", ((string)(null)), table70, "And ");
#line hidden
            TechTalk.SpecFlow.Table table71 = new TechTalk.SpecFlow.Table(new string[] {
                        "Hr_00",
                        "Hr_01",
                        "Hr_02",
                        "Hr_03",
                        "Hr_04",
                        "Hr_05",
                        "Hr_06",
                        "Hr_07",
                        "Hr_08",
                        "Hr_09",
                        "Hr_10",
                        "Hr_11",
                        "Hr_12",
                        "Hr_13",
                        "Hr_14",
                        "Hr_15",
                        "Hr_16",
                        "Hr_17",
                        "Hr_18",
                        "Hr_19",
                        "Hr_20",
                        "Hr_21",
                        "Hr_22",
                        "Hr_23"});
            table71.AddRow(new string[] {
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1"});
#line 202
 testRunner.And("enter values into Actual Hourly Arrivals By Day Of Week for Tuesday fields", ((string)(null)), table71, "And ");
#line hidden
            TechTalk.SpecFlow.Table table72 = new TechTalk.SpecFlow.Table(new string[] {
                        "Hr_00",
                        "Hr_01",
                        "Hr_02",
                        "Hr_03",
                        "Hr_04",
                        "Hr_05",
                        "Hr_06",
                        "Hr_07",
                        "Hr_08",
                        "Hr_09",
                        "Hr_10",
                        "Hr_11",
                        "Hr_12",
                        "Hr_13",
                        "Hr_14",
                        "Hr_15",
                        "Hr_16",
                        "Hr_17",
                        "Hr_18",
                        "Hr_19",
                        "Hr_20",
                        "Hr_21",
                        "Hr_22",
                        "Hr_23"});
            table72.AddRow(new string[] {
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1"});
#line 205
 testRunner.And("enter values into Actual Hourly Arrivals By Day Of Week for Wednesday fields", ((string)(null)), table72, "And ");
#line hidden
            TechTalk.SpecFlow.Table table73 = new TechTalk.SpecFlow.Table(new string[] {
                        "Hr_00",
                        "Hr_01",
                        "Hr_02",
                        "Hr_03",
                        "Hr_04",
                        "Hr_05",
                        "Hr_06",
                        "Hr_07",
                        "Hr_08",
                        "Hr_09",
                        "Hr_10",
                        "Hr_11",
                        "Hr_12",
                        "Hr_13",
                        "Hr_14",
                        "Hr_15",
                        "Hr_16",
                        "Hr_17",
                        "Hr_18",
                        "Hr_19",
                        "Hr_20",
                        "Hr_21",
                        "Hr_22",
                        "Hr_23"});
            table73.AddRow(new string[] {
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1"});
#line 208
 testRunner.And("enter values into Actual Hourly Arrivals By Day Of Week for Thursday fields", ((string)(null)), table73, "And ");
#line hidden
            TechTalk.SpecFlow.Table table74 = new TechTalk.SpecFlow.Table(new string[] {
                        "Hr_00",
                        "Hr_01",
                        "Hr_02",
                        "Hr_03",
                        "Hr_04",
                        "Hr_05",
                        "Hr_06",
                        "Hr_07",
                        "Hr_08",
                        "Hr_09",
                        "Hr_10",
                        "Hr_11",
                        "Hr_12",
                        "Hr_13",
                        "Hr_14",
                        "Hr_15",
                        "Hr_16",
                        "Hr_17",
                        "Hr_18",
                        "Hr_19",
                        "Hr_20",
                        "Hr_21",
                        "Hr_22",
                        "Hr_23"});
            table74.AddRow(new string[] {
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1"});
#line 211
 testRunner.And("enter values into Actual Hourly Arrivals By Day Of Week for Friday fields", ((string)(null)), table74, "And ");
#line hidden
            TechTalk.SpecFlow.Table table75 = new TechTalk.SpecFlow.Table(new string[] {
                        "Hr_00",
                        "Hr_01",
                        "Hr_02",
                        "Hr_03",
                        "Hr_04",
                        "Hr_05",
                        "Hr_06",
                        "Hr_07",
                        "Hr_08",
                        "Hr_09",
                        "Hr_10",
                        "Hr_11",
                        "Hr_12",
                        "Hr_13",
                        "Hr_14",
                        "Hr_15",
                        "Hr_16",
                        "Hr_17",
                        "Hr_18",
                        "Hr_19",
                        "Hr_20",
                        "Hr_21",
                        "Hr_22",
                        "Hr_23"});
            table75.AddRow(new string[] {
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "1",
                        "2",
                        "3",
                        "1",
                        "1",
                        "1"});
#line 214
 testRunner.And("enter values into Actual Hourly Arrivals By Day Of Week for Saturday fields", ((string)(null)), table75, "And ");
#line hidden
            TechTalk.SpecFlow.Table table76 = new TechTalk.SpecFlow.Table(new string[] {
                        "ESI1",
                        "ESI2",
                        "ESI 3",
                        "ESI 4"});
            table76.AddRow(new string[] {
                        "1",
                        "8",
                        "55",
                        "28"});
#line 218
 testRunner.When("What is the Emergency Severity Index (ESI) breakdown for your Emergency Departmen" +
                    "t?  then click on  I\'d like to enter the data manually  and ESI pop up displayed" +
                    " then  enter esi values click on OK button after click on OK verify  Click to vi" +
                    "ew ESI  link", ((string)(null)), table76, "When ");
#line hidden
            TechTalk.SpecFlow.Table table77 = new TechTalk.SpecFlow.Table(new string[] {
                        "Los_for_Addmitted_patients"});
            table77.AddRow(new string[] {
                        "147"});
#line 222
 testRunner.When("What is the Length of Stay (in minutes) for Admitted patients in your Emergency D" +
                    "epartment?  question appeared, enter the value in textbox and press enter", ((string)(null)), table77, "When ");
#line hidden
            TechTalk.SpecFlow.Table table78 = new TechTalk.SpecFlow.Table(new string[] {
                        "Los_for_Discharged_patients"});
            table78.AddRow(new string[] {
                        "200"});
#line 226
 testRunner.When("What is the Length of Stay (in minutes) for Discharged patients in your Emergency" +
                    " Department? question appeared enter the value in textbox and press enter", ((string)(null)), table78, "When ");
#line hidden
            TechTalk.SpecFlow.Table table79 = new TechTalk.SpecFlow.Table(new string[] {
                        "Arrival_to_admit_decision_time"});
            table79.AddRow(new string[] {
                        "150"});
#line 231
 testRunner.When("What is your Arrival to Admit Decision time (in minutes)?  question appeared, ent" +
                    "er the value in textbox and press enter", ((string)(null)), table79, "When ");
#line 236
 testRunner.When("Shifts questions displayed then do import shifts", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table80 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phy_cost"});
            table80.AddRow(new string[] {
                        "350"});
#line 238
 testRunner.When("What is your average cost (in dollars) per Physician hours? Please enter 0 in cas" +
                    "e of no cost.  question appeared, enter the value in textbox and press enter", ((string)(null)), table80, "When ");
#line hidden
            TechTalk.SpecFlow.Table table81 = new TechTalk.SpecFlow.Table(new string[] {
                        "APP_cost"});
            table81.AddRow(new string[] {
                        "300"});
#line 243
 testRunner.When("If you use Advanced Practice Providers (APPs), what is your average cost (in doll" +
                    "ars) per APP hours? Please enter 0 in case of no cost.  question appeared, enter" +
                    " the value in textbox and press enter", ((string)(null)), table81, "When ");
#line 248
 testRunner.When("We have defaulted your average cost (in dollars) per Scribe hours to $20. Do you " +
                    "want to change?  question appeared then click on  No, I want to continue with th" +
                    "e default average cost per Scribe hours.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table82 = new TechTalk.SpecFlow.Table(new string[] {
                        "Targeted_Phy_PPH"});
            table82.AddRow(new string[] {
                        "2.5"});
#line 250
 testRunner.When("How many patients does your Physicians see per hour (PPH)?  question appeared, en" +
                    "ter the value in textbox and press enter", ((string)(null)), table82, "When ");
#line hidden
            TechTalk.SpecFlow.Table table83 = new TechTalk.SpecFlow.Table(new string[] {
                        "Targeted_APP_PPH"});
            table83.AddRow(new string[] {
                        "1.25"});
#line 255
 testRunner.When("How many patients does your APPs see per hour (PPH)?  question appeared, enter th" +
                    "e value in textbox and press enter and verify the  Your APP coefficient calculat" +
                    "es to  value", ((string)(null)), table83, "When ");
#line 260
 testRunner.When("We have defaulted your Scribe coefficient (efficiency of providers Scribes increa" +
                    "se in percent) to 15%. Do you want to change?  question appeared then click on  " +
                    "No, I want to continue with the default Scribe coefficient.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table84 = new TechTalk.SpecFlow.Table(new string[] {
                        "Phy_First_hour"});
            table84.AddRow(new string[] {
                        "3"});
#line 262
 testRunner.When("Do your Physicians have a higher than average PPH during their first hour of the " +
                    "work? If YES, please enter the PPH during the first hour. If NO, please enter 0." +
                    "  question appeared, enter the value in textbox and press enter", ((string)(null)), table84, "When ");
#line hidden
            TechTalk.SpecFlow.Table table85 = new TechTalk.SpecFlow.Table(new string[] {
                        "APP_First_hour"});
            table85.AddRow(new string[] {
                        "2"});
#line 267
 testRunner.When("Do your APPs have a higher than average PPH during their first hour of the work? " +
                    "If YES, please enter the PPH during the first hour. If NO, please enter 0.  ques" +
                    "tion appeared, enter the value in textbox and press enter", ((string)(null)), table85, "When ");
#line hidden
            TechTalk.SpecFlow.Table table86 = new TechTalk.SpecFlow.Table(new string[] {
                        "FTHoursFrom",
                        "FTHoursTo",
                        "FT_LOS",
                        "FT_PHY_PPH",
                        "FT_APP_PPH",
                        "FTesi3",
                        "FTLOS",
                        "FTPHYFH",
                        "FTAPPFH",
                        "Duplicate_Shifts",
                        "Current_To_Time",
                        "Proposed_From_Time",
                        "Proposed_To_Time"});
            table86.AddRow(new string[] {
                        "09:00",
                        "21:00",
                        "90",
                        "3.25",
                        "2.75",
                        "5",
                        "90",
                        "4",
                        "3",
                        "2",
                        "18",
                        "05",
                        "19"});
#line 272
 testRunner.When("Are there any other areas in your Emergency Department?  question appeared then c" +
                    "lick on  Fast track and answer all the questions", ((string)(null)), table86, "When ");
#line 277
 testRunner.And("click on No,That\'s All button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 279
 testRunner.And("Clinical Work Distribution for Patient Encounters  pop up displayed then click on" +
                    " OK button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 281
 testRunner.When("Save Model  pop up displayed then enter mandatory information and click on Save", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 283
 testRunner.Then("model should get created and success message should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
